### ISSUE TITLE
Support for `py -0`

### ISSUE THREAD

**Issue by H4CKY54CK** [Lucas-C/dotfiles_and_notes#4]
Why not a `py -0`?

**Comment by Lucas-C** [comment]
This a request about the [py](https://github.com/Lucas-C/dotfiles_and_notes/blob/master/bin/py) CLI script ?
What would be this `-0` flag behaviour ?

**Comment by H4CKY54CK** [comment]
List all installed pythons. Something like

`ls -1 /usr/bin/python* | grep '[2-3].[0-9]$' -o`

**Comment by Lucas-C** [comment]
Added 😉
